FROM node:20-alpine AS production

# Add a work directory
WORKDIR /app

RUN apk add --no-cache yarn

# Install app dependencies
COPY package.json yarn.lock ./
RUN yarn install

# Copy the rest of the application code
COPY . .

# Copy app files

# RUN yarn build
#RUN npm run preview

#RUN curl -IL localhost:8808

#RUN npm install vite -g
# this works here but not in dockerfile RUN vite build --mode staging so replacing with npm build
# RUN npm run build

# Expose port

# Start the app
CMD ["yarn", "dev", "--host", "0.0.0.0"]