version: '3.8'

services:
  react-admin:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "5100:5173"
    environment:
      - VITE_LOGIN_SERVER=http://localhost:4010
      - VITE_API_URL=http://localhost:4010/api/v2
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true