replicaCount: 1

app_name: opsapi-ui
app_environment: test

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test-opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: AgAb7cQnY6TNn2qf0FyyvnEQpCriaoxiqdOwk6cK/QtXrtIk/GPYYE8g39Ht/wXdURHUANIKGYl8JgY31n1jpLMFhcuRRIEt+PtuW4EOL1CDk7TZ3vEo6YHyZdupydtHudIZHQQ2L3rMRhM61/7Hdcxp+XTqvk00Lf+8MMxNJoT7akOjXUvYsKICXXL6T+VMNoecUUKeiavRWqJaAOa1dWsIHNoyPP8BXUnljx5GOHbfTk0KIBtPG2ijOv2Cr150qQ01+8yZlxaOm6M+62RN+wBeonDfOI6X/r1yI+xJ5bPJjcduGa5ChH8znXCA/1dhx66wTXUo6hOonVa0YNBR5EmH85AOEBI49q+vCMzM9H4W1RIYpVBY2+RR1DqTw0KvndmFQyS1f72d4WX4mzfdxPWryyEJDuxDihG6lqQ1keaPs23diWwLs0FEAGy9uUtop8jspPukPvIVML6MHGQINoysIftvGdnWeLZ60zrFoddrQKAUHvdvCAMogJqcSZO33KPcX0fy7xVtAG5YPE3DUzF1uKRurjft21FD6Bqouz9oAM4pNEb1fXLylLShDEDwpcXEXNgfWcCuYEKYMxM7B0fOcp4fkoliqu3X9BB7q+E+xzDzYDb7mP7vRR/A3EW2ES8zuOFaoDJgp8BzLf6k03aqBrW0nXRA8i0c81dyC8iYDpw+GMmryzfd6nYxKwXyfoYL6UVAe60xwW/uxfyi07CyYri680WaepXVPCWnI7aG3c0vxC9PkFXrDaJAsdju+Ya8D3gyZVtYeoosawuimc19nEL/sxukB/Fgaz1xFckA6jRAubtim0PGzVKvw8R95HyxI78ravpYEW3O/RPLHfjISfpSewnGao2tn9cMvbxcS4FjO/tCzwbViqbgdpRefHQUbUNpeyjDPv+vFIuKCkwYj9z/YTHyrB7QcgoVXNz8F3Q4