replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgAGJ+wCBKDw7hofDfgeDw/6B+mCFXZiBK1FVoQkKPKhwbcvMsA2fH4diXKnUdHUE+qv5Wj4G3oxohf+iejJQ4FRH9AoJfaMUDxgFZYZ+h2lppzwG+/FLirAm532kF1e5XTZPo7mROv6wmVGkqlbFLv3B9N2X1J91vWKUSpgU0nGw6b1Xb2LjoUlaypAjkh5HQ32r2LxBATSt3YYP/1SO8c3qcjY1oXi3nzZl2lPtHz1OvlZ71za2ZlnK4o4dobABd8ygINj5YqCR9qWHxfQgXVMiXjWPzBvrDYvz5EyJViX3mp7HPIzTir6aPhKy+PD55Ew/eOxWoMRaoAOMHTVOTBn++METb8yZYatlLa7BHl/0ctB/IJnmsGoB8e7JJh9Y9Gc0/kPHzBfALhzt8WamOiLA+8ABTOPM4lqkG6iag1YbiXD2UBdKOC6VNbIsQk/IdXVIKyxqj0iezw+jpZu8ld+DizWTUaT0MzO2qIUboS/xxyW+CMC0nsrTIB815dZ1wvRV51dH7uhz/3m96amtKVdhgTkU+EfSd2ZACF8UFrcIElPhMEWhDDiNGgmi3bX5O2swOOz69dIcZwaqQxL/peh+zNr+VKXMtiJVwECWxgqzcJoPeVcOzkEKwcy9rNp39FlQLa+rcmpmehQItKrfCopfo3vfug10LcQtQetTb1GNcD0n/EWKEpjLZFOZkts3HGbX/Z2hxo85OnwqwOWIrlXPHyyiTUhdk1vqnJGol0IiFxPIq4rl8/dZUf1nHDN+rwa7Bw+yusnkeNcLmMJt2BvSHebFaRO3QsEULjO1MIrqBrS4d07asy+0vVKCtBC9VDedvEDWqInDtm1jsAuPFnx2lQGbwlFtkEqgGvTbv2vx3XM+yff6o/D+97ok9vnrcouiDgKo9vGSULuqFVaLxjahk3mnTIGDlAv"
