replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgCfghwSfaI7nSKXnkpazhlTImtnZUAl5+tISSvyYa+vBkb6vvu8nllaZP7hSnGX/3GZLTtTnbNnspgQZS2rGitebWwp9YDuKv6HV+9tVqlpxdoc9TR/hbsgxWuyR3pDNUJ/slow0Gz8sLy3kV8UOr0e3LCVkiEmqVdXjvZyN6vsDeWhI68qfkLt2jZ9XdW5aW+8KOz3F9mlfvJnzaAjV+rk2/59YcPXAEN1HMkPY2m58B8Buug27AaStx5qKq5wHUuv6We0f1lyXvwXbHZoB806L6tLJw9oC6+kBKi11NSnx8ODldw3tvJCuby2lkDOp4WLLsBXMt4NDuGt6Ded4LgEcNoNZwIk0pceHSgsW4YKDC4OdYPrT3lrxJDFViXJJzTBVEAxQDEs14POXI/zHMMYwLgLkqXjz9E07Lpe+VMB+JgUFZd8HCw83QSfoW0stn/5zMxI6SSsa+Dj++nJdCv8aSyNPo3c3m0zxjYV9jN/8/S4Skv0QHTaDQaAtmeB/Llixi7DOI8b6Z/OzGA8kTbqZF72Ql7Ti7eKCCCf8PQaC/5RwYLSogHaZUX8Mh0Q9dciTfOJra2Zu2q63/Xtu7WxEeFyZwAeMiKCU/cAQFeEEESWEuccX5QYTTbG/rAvRyL0sEt9jW73ryFJIR/RzXMv72xwnh0kP6YwCPr0bNjR23EUpSLvu9o0LUiNMq6mYtOUSPJpkl6JsigHfq5VJ4uOrn+IhH9vFuzjWXGZVEl7L6DqrR1iFTbN2wwqMw+lGOiRzIhK9SezGiIrCCvcA2NZy/JGeuKpiwO3gYsNWi7GHsXcM5BDzT1ijBrzJFnsyVjgWBwWGc9ze7cOqilWRKo/j7Ex/L/RP7u0+LYI7QCo0OeQwhzdj7e1KZbBOL88SmR6wk5qk1/IbfvfQCqYRe5zFh9euEydT54Q"
