replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgBEZHgKRvomwfdl7iY8xT3rXpJwTZo0Y66I7i7iKN6UUpZCxnRLx6mX3dV6M4hXKNaG2dBCm1ANfKk82m8jbB/Iztkn4ZX/vU2Hu45DTHNnOyZQkTNqgJXd008fEzsDjNiRuS/JRvkz68X5ii4en0lXBQ++2KfGGLgY7cprw0O60GfRAA1OD7k2OQSk0D4al2KvJz64eCJJMD29qMVjyBYA0OM5h2PbQfKVZrckfwrUnK4DWuo0jPqhwFW/irmVkd6/zvjKP9JXT2txjhZPDcCMiyPCPdNjXl/bZzeNKIdtDk5lcCM4LHiAmeJLHIxSIkXWBA19IBGQbT2wKB7hCedQcQ2gYO1FR4Cr5DUIglNWYrrVD8KCLpZWKQQ9pC86bpifOx3JUfpK+PyuLcNi2fG6nX4p3oc3CHAQIKmN2G12p5rA/rA4CoZKQZGeENW41mXAeo7i3ofbDDoqFjjDPeL+7buf4A2stUlUNhWJ7sw5cq1PP5D+bEkVm1aFTH1ow6kMgLBvn/fv6OO0RqeEOKnSSww+CfHmhyGVqI8s0m6gfECAEkjqarTAGpY2w/g/RPEumHgcCHYd7FL5NMFs4+TqPqhCyZ2G3U0u45y+cxkSoK7C64DWDUajd6zb6q6uDZZCMIoPjFU0UJ1Xeb+M3rEV5bd50PTihLaZx89nO/1ctvI+u/XR6zn5MLuEHjhY3Uwwc6KnXyHPWVgFkkIvi9nKWul0yaRD90yRPNBgjNxFscXh0DO7WUN0QcSLHLYtGz/JOym3EFDoW6h2zqNQOyqzhqiLyQw3DbMZkieWYX+mvxx1t9b/iTOJ6GBIec8kYsLsq67vkSp9/MmFFwBzpA2hAmm+BAeH6Dz6SgI6JitPpiuWzZrdCm8QVTjD8va169CCxqV35+MhXv5DS8qZVCqURymJrLqmzMwF"
  
