replicaCount: 1

app_name: opsapi-ui
app_environment: test

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test-opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: AgC6JC9MPnOTFsoYDkUDE00YjaZ2HitW2oC3iCmfhl/kWxVTBs79+Ll2oGtrwHy/H0AjDA4F6dX+bwz8gJf/+0YGDGBXQ2MHCscMfPxgEIvnNN6Hbj36Ywg8RRuW0I2lGEmNlfBlpGE73aHeNJZDTyIieIrUZvLzoTNo7YBrWWXa/I1wbCmlDenWNBc08jSYwdtfbNUO13vZjVDm0GK1uRg67U5KVf/X5wSNxhMRtMXfwjhL69PYR9pAz42AZdvCjnMyjvgmHNJvZrR8QPD0mP7sW5YdbTFD3/3bA7BauRrXT/g1W7T22NiDwDXL1OKCqM7PjleFYdgDcYwsITF48vYzxJaKPhrvOuZu7YFDF43uH2RBknOHw7dNWn5u5Y3feeuyB5T7++QHg1oLhOPdihbXAL2hct/RPMDfxxE3fH1jLbaMJ75CjLCnaSKhlHBLixXv7PpgLdO+zdsUxnz18KLGHH38CydBNyXHAB4O1ZXsyoN4Srpo6iTTXb9ZkVitRTRCq3wiZ+sS9FejOPne5Ozwk0sA4UMvM1zM3Ry5azC3IR4qt85oCfjCNBKbnOPPV+2aT9Yz8ibicEdwV94rztuqCHEnei5bmULIW7x/uU62amYEikUzDJ+5GOR7RCt3/g4U+D6fTaGDSrRnmTTqYOOUJqFeC3i8oRrTZbesRnQNiJ2pF9w311Yie5fDpzyNjiWg2CT6m/TrfdMfcbDx05imj+hJUsD5tOrJJoEqxTomMBSN4ZVrUj+NKg/jYiQtgetVr/Vx4IloPcX9MdjULYl/Q17fVqjrSXuFq1+CR8bX7FzWOgmuAFP/tX4zKG7MOYNsMG3jPMdEXaylUnTkVwqWirZItiWKsaRP+3tXor8r7vJG2lcWkRudxRb9jAMUA9Y4qcFSHMxfbtAhF8Cx+fE+eP/yx5F8wMT11jU4kgWP2ub1