replicaCount: 1

app_name: opsapi-ui
app_environment: test

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test-opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgBlgOXLsmjKdS//UzrOhGG/HQCGknEhD/GhJdONG785w9eeB47iqRTwhr2ZCHaSW5pI8EkLkOffqsNXg9CIrjwQ4bZrDNXt35r8yg3gHtdzwV1/y9Cx5aB1iSQwp55Mbkf8btmBgp1WI78JRudrh1SLMwrbMS09UuIAx5VZJ1xxHGr1KgKsuj9d0mYDQy8zFgt6tbfHZ+A5bATl5+vad62/lD+d+Kth3/CQX99fU0UhDDxgY1CMAb5+Kr/wwpZZcMCCmbaaNhsmP7CG4hwk6UxfRR8OE19QmMFM7jpn1Ig5qsRiBF5Am4JE365/EDF7Gw96z+wLMLN5Hxj2CUV0nEl7w/AQ9XHAftmgSk05FUs4Y+eZY+6gIJcgEEp0c9fNgYpp3F7PV1sMeqLKHxM5bRDoM0rGz8wytvmFoLKhuCtbtmtFfB2TSYQ6WF2rLjTsZQR9biIuQFZS2SQwQM8DII+eYxrW61GcYV5A0lRFw24xCe2U1zBKmZlO0jKlqTC4T+/I0dVuLNAkqUKBuJyO66JFfbV9iuog9vUGCt3EhBRmzDWUUgtl1wrcCHdPa8q9BrZ6Tz37bJLFVFXAXB0NfOklNpCiA+bJ2MLCeHbmyWUk/Ez273l1lnNVyxcT503wRzFZ7tvajuA/k4ctOxZkuGALrMPekemCu5sElYAgwuxi7EqhwcK5x5IJGXsaEJd1rlfrB9pNAILBBn8MCVsXZGW6jkkkGq44QpooK5HnVHHv1WHyDlmESWIcBDxQ2nFy9it0MPd/Cpc236dFxoOHb9uOOdnzh/mUedHJC3pH+NgXNvcMrpyDzLjWPIK6daLHzrZ8hBJbtGXhHTEpwk0MlwGFdak+wNzH54pqaLjVrvwbF8fwWSIO2KszwZZRTfQtycpmcc4+qmWvS/4jAUuGXVXj50tAlZjEbHv9f8iyl3i4nosE"
