replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test-opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgCQxXtXRLuKU6DwKJ1ZNe7epRqEYFXZIyhXBJFIsl9ST4cJlR2hJS2x38HpzFXg643OcRRzSBPYax1kUzNZ9HCtmE6YftkXeMbogMSVpH+pyNSN+7UhWh6DTvnrNn6My8T3Yno1D849gsBQuIvjZhB8tpRMQjiBFrprrZE6Hrz3XW+Ptq/D9KOTlyM+oVUfaIiEjGi97s2KZsstidcDUDo4hXRjPcNBKmsHOoX9JGmHHS+bp/IWH92quSD/1L1MV/P9JJPJXekr3QNw4EkBSCM046oObeKLSsbA9ogAW+JzWmO9SLJkblDQAULMn+FlsDKyFAljPdkRPNizYQXFQCHoihp0tpCHiObgtLxexepZLRY1hmnQVLRdnTNpkSSo1RXMN6vDl+E/YEPFOxZsDmwRyGXEYDEoBZ45hZuf7PCVHnJKoGX52Tvkw12tQKKFO5ONBcXWH9+o7Q/8hh2hHzsT3bwInv1bwveI2CstYaio+OuzaRN+A86kl93jU2V1LTnyNpj3xjs7ralFTL6qrSl7Q8z7bPuPBL9LUdvp2/0iNVca0/3crhtQHUlinQdIlxE8YjNOSscTQVcda3zAlYJUl+txEzjqG17zTv10LpoPAz3N0cDaXYBRyejBj0htcn8cP/L0izfj7cPHErVACNHRItrap04kVkR7FpUfEKFv4aOR916FeNm5vY92uKI0M8Q5YPXLAdb/Qr0YEgzhUJiLLRhpw8GHwgPUpeIn3j622w/dsf7NMPODqrUftN2uT8YjBsCoXmKAy3upRkxbrT+tYYXXkg/U4pF0rFysYt3TxOmGaE+UE94IsiAe3OKMhQiFDIEdY976Bxem8hft/fIfUkXghRlVTcPM1ofLsqKNgqGx6N4egjD34RzJgBEcfNOPPs4LvKwDlOypssFWzq61OoOZ+PKrTLBtm6OaHKBvaMLX"
