replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: opsapi-ui.workstation.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgBipVNcrC5SlogrH37nk/F84G5+WTbWhG1mISNm6I4Wg5oiJDVHeQ7RpQiJX0nPW8LpqZEbLP1hGW6nX3XxiK83H5CvpKTwh5WPzPx3M9/syIlSoV16ogy0TBAjU9wQACcYBEjVTGuICj6bq4fmRJ8Q36fQG6HpuaC9dGqwvGfEA8Foi63SKlno04v60pPIdq+hsm0Pgp4Rm56KBvKe9vgkQN+GLECl9yv87U2nmiNgngAnn1eq+9j6VLYQ0vFLVGeXBWbPya0DEDDnNVE4i6SCM42WejWnf7UppBLPj3U67ZfpdRZk+mTp0YmZGm08k0eAKUcWMiWfFChsKyqHtopSj4gCr0tRPfAJDF/AVQfrtpM+vCGzUlNG3i8ZxjcNlCZW+8jInFDZJnguS2xYDevURSc84382Xx2kJdDOJvY1rw47gnfU4QLz8KzMQjvjkS/4BvfspJVQMyrcBpggvpJQtJzVEVBggeIfdRKEWn2pYriGbdXe/JoCsR8ZyNwl+p9vBeTpQnVsxF3qG5RaXPIZD+5iLAmha2Y1SZH2eHl4rebnf6I5Y/NU+nggspOB1AB9bmXvbKCI1x9gwBWeY+f3of1hlXOc/bq5l+kdge0s4hGFA929Ii+K07GBMudcw45Q1g7UcSGDAu5k1VM0ySkbHZMlqESOpv8GUE6qHgk+XMvtfCMmFz8I9FGnRuYJAcoeC3BuW6zyPEZMRBy7cdUQl/ZvzeLPKnc/sMQdJ/8aMi2mjXs9Zv4O3uA30e0E6r2ix5DTK8OxXe0AS5Ww0x/89MBsMWj4m67CRHYTc+ggNkIxvHby50YjNuhzCEmdI1MS0s0UC36NURrAOYcjKLRkAvyrr1fEPJsge8qUzVoyGWI58cifJhLPSrZMpd2XvcaguGid319/Zz561F7y83ZnEgR4gSVGF8sY"
  
