replicaCount: 1

image:
  repository: bwalia/opsapi-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: test-ui.opsapi.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  secure_env_file: "AgAjTrr5FCtvPdrb4gGOl6qSKuYeOtxiDPfVLTTDaTTJmTw+T8/fFCdEDoJ5N/etW48HAlepMX9MPxVBY0XvG7qkh/5sYK/4l3KVIcCbhFaIDMW1lXPQt4vwhw+HhRzFRDhEEILhHIATi6sQjcgp4Yi8rCPQYRmdCAhOQZXkua/MFP+WZHeaahl8MuqIX1x0KRvAHWBYD/e84VKT2O5CHRJ06F5fzynw5eihhkJURlYb/aO2giB6FmETyqY1ekeqOj3NHs7EPjw5h8cGUJhb3CbhBroU5URh2MRpO54ApkOuJb+rsMtxRMSxhd5OSPPEZwx5rtw4uED0jVpFz8+eNmh0lgwPafHDvqFx9PpQKJ1QY+kxGAV84b5RqOyG9h7P8sP2mOF4/MZ3Jjp1VPdrHs48sFkncoj05osYO53fNN+s5F2QLkO1Sj96y24EatxJ60BGeAgeUMuiL70ts3OXSmJCsIEJ7Qbaqs124G4mqsJLSsCvb2CQq89yPBLnIZqRInxABLVSi89WSqMdQUgp3BrffoBgaa8ldjhCspKK2pA3ytBKVOt8RVGFf0ljFQijSax3nTSDI9L194nJR8xZHIAAopV5EVavEnnFmA/iA0w/lDn9d3hiJcrRRMMPI89bAH9GFSdFcTfsFqQOV2igkhrSLxM9awW0bnZUUCxQLsUExoeXr/T4bBKWewvSLUvCpgFFTZaGoknG9bT5d0ZMB9ndIu+ama6urPMnlNeLkJS+XQAeLvRa0/np7zNY5lUBxGTA/E6lnUWbz3t2Ck2EOID2eDDVrePdqQBmHDtMgwke4SbVog=="
