apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-openresty.sh: |
        #!/bin/bash
        set -x

        FILE=/app/.env
        cp /tmp/secrets/.env $FILE
        echo "==========================="
        echo "Openresty whitefalcon Src copy to /var/www/html Complete"
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        echo "==========================="
        echo "VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION" >> $FILE
        echo "==========================="
        echo "Update openresty config file for this whitefalcon env"
        echo "==========================="
        echo "Restart openresty nginx"
        echo "Rebuilding yarn"
        cd /app/ && yarn build
        echo "Rebuilding done"
        openresty -s reload
        mkdir -p /opt/nginx/
        openresty -v 2> /opt/nginx/VERSION
        echo "==========================="
        echo "Openresty whitefalcon Nginx Bootstrap Script Completed"