apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}
#   namespace: {{ .Values.targetNS }}
data:
    bootstrap-nginx.sh: |
        #!/bin/bash
        set -x

        FILE=/usr/share/nginx/html/.env
        cp /tmp/secrets/.env $FILE
        echo "==========================="
        echo "nginx opsapi ui Src copy to /var/www/html Complete"
        DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export DATE_GEN_VERSION=$(date +"%Y%m%d%I%M%S")
        export VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION
        echo "==========================="
        echo "VITE_DEPLOYMENT_TIME=$DATE_GEN_VERSION" >> $FILE
        echo "==========================="
        echo "Update nginx config file for this opsapi ui env"
        echo "==========================="
        echo "Restart nginx nginx"
        echo "Rebuilding yarn"
        cd /usr/share/nginx/html && yarn build