apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "stat -c %a /tmp && ls -la /tmp && cp /tmp/configmap/bootstrap-nginx.sh /usr/local/bin/bootstrap-nginx.sh && chmod +x /usr/local/bin/bootstrap-nginx.sh && bash /usr/local/bin/bootstrap-nginx.sh"]
        volumeMounts:
          - name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}-vol
            mountPath: /tmp/configmap
          - name: {{ .Release.Name }}-vol-{{ .Release.Namespace }}
            mountPath: /tmp/secrets
        ports:
        - containerPort: 80
        # env:
        # - name: VITE_API_URL
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Release.Name }}-secrets
        #       key: VITE_API_URL
        # - name: VITE_LOGIN_SERVER
        #   valueFrom:
        #     secretKeyRef:
        #       name: {{ .Release.Name }}-secrets
        #       key: VITE_LOGIN_SERVER
      volumes:
        - name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}-vol
          # Populate the volume with config map data
          configMap:
            # `name` here must match the name 
            # specified in the ConfigMap's YAML 
            name: {{ .Release.Name }}-cm-{{ .Release.Namespace }}
        - name: {{ .Release.Name }}-vol-{{ .Release.Namespace }}
          secret:
            secretName: "{{ .Release.Name }}-secrets"
            items:
            - key: env_file
              path: .env