---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Namespace }}-secrets
  namespace: default
spec:
  encryptedData:
    VITE_LOGIN_SERVER: {{ .Values.secrets.VITE_LOGIN_SERVER }}
    VITE_API_URL: {{ .Values.secrets.VITE_API_URL }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Namespace }}-secrets
      namespace: default