---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    env_file: {{ .Values.secrets.secure_env_file }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ .Release.Name }}-secrets
      namespace: {{ .Release.Namespace }}