apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-{{ .Values.app_environment }}-service
  labels:
    app: {{ .Values.app_name }}-{{ .Values.app_environment }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}
